%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /Users/zwdu/Documents/GitHub/sir/pholme_sir/Withinhost simulation.csv
%
% Auto-generated by MATLAB on 01-May-2020 15:57:15

function ViralD = readViralFile(filename)
%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["HoursPostinfection", "logVHour",  'cum_logVHour'];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
ViralD = readtable(filename, opts);
ViralD{:,3} = cumsum(ViralD{:,2});
ViralD{:,3} = ViralD{:,3}/(ViralD{end,3});
